[versions]
kotlin = "2.2.0-RC"
serialization = "1.7.3"
klasp = "0.0.1"

[libraries]
kgpApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[bundles]

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jgp = { id = "java-gradle-plugin" }
klasp = { id = "org.haliksar.klasp", version.ref = "klasp" }